var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

window.SimplereachVideo=function(){function v(b,e){var a=this;a.w=[];a.F=b||{};a.uc=c.Gb;a.R=!1;a.yb=e||c.jb;t.fb(a.yb);m.j(b[c.Aa]);b[c.v]=b[c.v]||u.current[c.v];b[c.url]=b[c.url]||r.qa();b[c.title]||(b[c.title]=r.oa(b[c.url]));if(b[c.url])a.j=function(){if(a.ub())return a.bb(),a;m[c.error](a.Qa());return null},a[c.Jb]=function(d){a.vb(d)?a.cb(d):a.Na(d);return a},a[c.Bb]=function(d){a.tb(d)?a.ab(d):a.Ma();return a},a[c.Ob]=function(d){a.wb(d)?a.eb(d):a.Oa();return a},a[c.zb]=function(){a.R||(a.o(a.M(a.M())),
a[c.Y](100),a.R=!0);return a},a[c.Y]=function(d){if(h.contains(a.w,d))return null;if(h.contains(h.W,d)){var f=a.g();f[c.i]=c.Z;f[c.Z]=a.wa(d);a.o(f)}else m[c.error](c.Ea);return a},a.wa=function(d){var f,g=h.W,n={};if(!h.contains(g,d))m[c.error](c.Fa);else if(!h.contains(a.w,d))for(f=0;f<g.length;f+=1){var k=g[f];d>=k&&!h.contains(a.w,k)&&(a.w.push(k),n[k]=!0,m[c.info](c.$a+k))}return n},a.o=function(d){t.S(c.N,c.Db,d)},a.bb=function(){a.o(a.Ca())},a.Cc=function(){return u.current},a.g=function(){return w.ga(a.F)},
a.Ca=function(){var d=a.g();d[c.i]=c.Fb;return d},a.ub=function(){var d;for(d=0;d<q.length;d+=1)if(!a.F[q[d]])return!1;return!0},a.Qa=function(){var d,f=[];for(d=0;d<q.length;d+=1)a.F[q[d]]||f.push(q[d]);return c.Ha+f.join(", ")},a.cb=function(d){a.o(a.mb(d))},a.vb=function(d){return d===c.Mb||d===c.Nb},a.mb=function(d){var f=a.g();f[c.i]=c.Kb;f[c.Lb]=d;return f},a.Na=function(d){if(d)m[c.error](d+c.Ia);else m[c.error](c.qb)},a.M=function(){var d=a.g();d[c.i]=c.Ab;return d},a.ab=function(d){a.o(a.sa(d))},
a.sa=function(d){var f=a.g();f[c.i]=c.Cb;f[c.Hb]=d;return f},a.tb=function(d){return!isNaN(d)},a.Ma=function(){m[c.error](c.Da)},a.eb=function(d){a.o(a.nb(d))},a.nb=function(d){var f=a.g();f[c.i]=c.Pb;f[c.Ib]=d;return f},a.wb=function(d){return!isNaN(d)&&a.xb(d)},a.xb=function(d){return h.ia(h.Qb,d)},a.Oa=function(){m[c.error](c.Ga)};else m[c.error](c.lb+c.ta)}var c={N:"edge.simplereach.com",version:"2.18.8",$b:"d8rk54i4mohrb.cloudfront.net",global:"SPR",Ac:"__reach_config",Jc:"__memo_config",
qc:"/n",Qc:"/t",Db:"/v",kc:"/event",fa:"/pixel?bad=true&error=",nc:"/iframe.html",ac:"/container.html",Oc:"000000000000000000000000",lb:"SPR-ERROR: ",ta:"100 - Missing url",Yb:"cache_buster",Fc:"__srret",rb:"__srui",J:"0",vc:"1",Ba:"img",Wa:"1px",width:"width",c:"undefined",error:"error",Ra:"off",info:"info",u:"SPR_DEBUG",kb:"//",H:"string",referrer:"referrer",uid:"uid",Zb:"callback",S:"jsonp",url:"url",title:"title",v:"pid",oc:"ignore_metadata",Pa:"meta",time:"time",la:"datetime",b:"property",
Ka:"itemprop",name:"name",ha:"canonical",link:"link",rel:"rel",Tb:"article",Ta:"og:url",pb:"twitter:url",Sa:"og:title",ob:"twitter:title",ba:"article:published_at",ea:"article:sr_published_at",ca:"article:published_time",ka:"datePublished",Xa:"og:pubdate",V:"pubdate",aa:"article:author",da:"article:sr_author",K:"author",Xb:"article:tag",Wb:"article:sr_tag",Ub:"article:section",Vb:"article:sr_section",content:"content",href:"href",Gc:"s",r:"r",t:"t",e:"e",x:"x",n:"n",sb:"v",Aa:"ignore_errors",zc:"preview",
A:"authors",B:"channels",I:"tags",h:"date",pc:"inframe",Sb:"ajax",Mc:"social_tracking",mc:"iframe",dc:"custom_tracking",Dc:"reach_tracking",G:"ref_url",T:"page_url",Rc:"user_id",rc:"manual_scroll_depth",bc:"content_height",Bc:"rd",lc:"fb",fc:"de",wc:"pi",cc:"csd",xc:"partners-api.pinterest.com",yc:"/v1/urls/count.json",Fa:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",$a:"[info] sending scrollDepth of: ",Hc:"[info] scroll depth not activated, not sending data",jb:"SimplereachVideo",
i:"event_name",Ha:"Missing params please provide a ",Ia:" is not a valid start event type.",qb:"Cannot have an undefined start type. Please provide a start type.",Da:"Please pass a valid number",Ea:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",Kc:"[error] Quartile for this video already sent",Ga:"Please pass a valid threshold number",Eb:"video_id",La:"length",description:"description",Pc:"thumbnail_url",Nc:"source_url",tc:"networks",Gb:"video",Jb:"start",Bb:"elapsed",
zb:"complete",Y:"quartile",Ob:"elapsedThreshold",Fb:"init",Kb:"start",Cb:"elapsed",Z:"quartile",Ab:"complete",Pb:"elapsed_threshold",Lb:"start_type",Mb:"auto",Nb:"click",Hb:"seconds_elapsed",Ib:"threshold"},h={Ya:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},ec:function(b){for(var e=[],a=/-|\//,d=[/\d{4}\/\d{1,2}\/\d{1,2}/,/\d{4}-\d{1,2}-\d{1,2}/,/20\d{6}/],f=0;f<d.length;f++){var g=b.match(d[f]);if(null!=g)return b=g[0],b.match(a)?e=b.split(a):(e[0]=b.substring(0,4),e[1]=b.substring(4,
6),e[2]=b.substring(6,8)),new Date(e[0],e[1]-1,e[2])}},l:function(b){return Array.isArray?Array.isArray(b):"[object Array]"===Object.prototype.toString.call(b)},log:function(b){window.console&&console.log(b)},Ja:function(b){return"[object String]"===Object.prototype.toString.call(b)},ib:function(b){var e={},a;for(a in b)b.hasOwnProperty(a)&&(e[a]=b[a]);return e},sc:function(b,e){for(var a in e)e.hasOwnProperty(a)&&(b[a]=e[a]);return b},contains:function(b,e){return-1!==(b.join(",")+",").indexOf(e+
",")},ia:function(b,e){if(!isNaN(e)&&!this.Ja(e))for(var a=0;a<=b.length;a++)if(b[a]===e)return!0;return!1},C:function(b){typeof b===c.H&&(b=b.split(","));if(this.l(b)){for(var e=0;e<b.length;e+=1)typeof b[e]===c.H&&(b[e]=b[e].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return b.join("|")}},s:function(){},P:function(){return window.location.protocol+"//"},W:[25,50,75,100],Qb:[3,15,30,45]},x={encode:function(b,e){var a=[];if(h.l(b))for(var d=0,f;d<b.length;d+=1)f=b[d],/\[\]$/.test(e)?a.push(encodeURIComponent(e)+
"="+encodeURIComponent(f)):a.push(this.encode(f,e+"["+("object"===typeof f?d:"")+"]"));else if("object"!==typeof b||null===b||"nodeType"in b)a.push(encodeURIComponent(e)+"="+encodeURIComponent(b));else for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e?a.push(this.encode(b[d],e+"["+d+"]")):a.push(this.encode(b[d],d)));return a.join("&")},decode:function(b){var e={},a=0,d={"true":!0,"false":!1,"null":null};for(b=b.replace(/\+/g," ").split("&");a<b.length;a+=1){var f=b[a].split("="),g=decodeURIComponent(f[0]),
n=e,k=0,l=g.split("]["),p=l.length-1;/\[/.test(l[0])&&/\]$/.test(l[p])?(l[p]=l[p].replace(/\]$/,""),l=l.shift().split("[").concat(l),p=l.length-1):p=0;if(2===f.length)if(f=(f=decodeURIComponent(f[1]))&&!isNaN(f)?+f:f===c.c?void 0:void 0!==d[f]?d[f]:f,p)for(;k<=p;k+=1)g=""===l[k]?n.length:l[k],n=n[g]=k<p?n[g]||(l[k+1]&&isNaN(l[k+1])?{}:[]):f;else h.l(e[g])?e[g].push(f):e[g]=void 0!==e[g]?[e[g],f]:f;else g&&(e[g]=void 0)}return e}},m={O:!1,info:h.s,error:h.log,j:function(){window[c.u]&&(this.O=!0,window[c.u][c.info]&&
(this[c.info]=window[c.u][c.info]),window[c.u][c.error]&&(this[c.error]=window[c.u][c.error]))},reset:function(){this.O=!1;this[c.info]=h.s;this[c.info]=h.log},Lc:function(b){var e=document.createElement(c.Ba);e.src=h.P()+c.N+c.fa+b.message;e.setAttribute(c.width,c.Wa);document.body?document.body.appendChild(e):document.head.appendChild(e)},gb:function(b){b===c.info?(this[c.info]=h.log,this[c.error]=h.log):b===c.error?(this[c.info]=h.s,this[c.error]=h.log):(this[c.info]=h.s,this[c.error]=h.s)}},r=
{J:0,ja:{x:0,y:0},isVisible:!0,j:function(){function b(){d.isVisible=document[f]?!1:!0}function e(){d.flush();window.removeEventListener("DOMContentLoaded",e,!1)}function a(){d.ready&&(document.detachEvent("onreadystatechange",a),n&&(n=!1,d.flush()))}var d=this;d.J=0;this.Ua(window,"mousemove",function(k){d.ja={x:k.clientX,y:k.clientY}});if(typeof document.hidden!==c.c){var f="hidden";var g="visibilitychange"}else typeof document.mozHidden!==c.c?(f="mozHidden",g="mozvisibilitychange"):typeof document.msHidden!==
c.c?(f="msHidden",g="msvisibilitychange"):typeof document.webkitHidden!==c.c&&(f="webkitHidden",g="webkitvisibilitychange");typeof document.addEventListener!==c.c&&typeof f!==c.c&&document.addEventListener(g,b,!1);var n=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",e,!1):document.attachEvent&&document.attachEvent("onreadystatechange",a)},Rb:function(b,e){var a=document.createElement("iframe"),d=document.body;a.setAttribute("name","spr");a.src=b;a.setAttribute("height","1");
a.setAttribute("width","1");a.setAttribute("visible","false");a.setAttribute("id","spr-iframe-"+e);a.style.display="none";d||(d=this.f("BODY")[0]);d||(d=this.f("HEAD")[0]);m[c.info](b);d.appendChild(a);return a},na:function(){return this.a(this,c.b,c.Ta)},ma:function(){return this.ua(this,c.ha)},pa:function(){return this.a(this,c.name,c.pb)},ra:function(){return window.location.protocol+c.kb+window.location.hostname+window.location.pathname},qa:function(){var b=this.ma()||this.na()||this.pa()||this.ra();
return h.l(b)?b[0]:b},jc:function(){var b=this.a(this,c.b,c.ea)||this.a(this,c.name,c.V)||this.a(this,c.b,c.V)||this.a(this,c.b,c.ba)||this.a(this,c.b,c.ca)||this.a(this,c.b,c.Xa)||this.va(this,c.Ka,c.ka)||this.a(this,c.name,c.h);return h.l(b)?b[0]:b},ic:function(){return this.a(this,c.b,c.da)||this.a(this,c.b,c.aa)||this.a(this,c.b,c.K)||this.a(this,c.name,c.K)},hc:function(b,e){return this.a(this,c.b,b)||this.a(this,c.b,e)},xa:function(){return document.referrer},oa:function(b){b=this.a(this,c.b,
c.Sa)||this.a(this,c.name,c.ob)||document.title||b||!1;return h.l(b)?b[0]:b},D:function(b,e,a,d,f){b=b.f(e);e=[];for(var g=0;g<b.length;g++)b[g].getAttribute(a)===d&&e.push(b[g].getAttribute(f));if(e.length)return 1==e.length?e[0]:e},ua:function(b,e){return this.D(b,c.link,c.rel,e,c.href)},a:function(b,e,a){return this.D(b,c.Pa,e,a,c.content)},va:function(b,e,a){return this.D(b,c.time,e,a,c.la)},Ec:function(b){var e=document.body,a=this.f("BODY")[0],d=this.f("HEAD")[0];e&&e.contains(b)?e.removeChild(b):
a&&a.contains(b)?a.removeChild(b):d&&d.contains(b)&&d.removeChild(b);return b},$:function(b){var e=this,a=document.createElement("script");a.type="text/javascript";a.setAttribute("async",!0);a.setAttribute("name","spr");a.setAttribute("id","spr-script");a.src=b;m[c.info](b);this.Va(function(){setTimeout(function(){e.f("HEAD")[0].appendChild(a)},1)});return a},m:[],ready:!1,flush:function(){var b=this.m.shift();for(this.ready=!0;b;)b(),b=this.m.shift()},Va:function(b){function e(){/loaded|interactive|complete/.test(document.readyState)?
a.flush():setTimeout(e,500)}var a=this;this.ready?(this.m.push(b),this.flush()):document.documentElement.doScroll?window.self===window.top?function f(){if(!document.uniqueID&&document.expando)return this.m.push(b);try{document.documentElement.doScroll("left"),b()}catch(g){setTimeout(f,0)}}():(this.m.push(b),e()):(this.m.push(b),e())},Ua:function(b,e,a){b.addEventListener?b.addEventListener(e,a,!1):b.attachEvent("on"+e,a);return b},Ra:function(b,e,a){b.addEventListener?b.removeEventListener(e,a,!1):
b.detachEvent("on"+e,a);return b},Ic:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.J},f:function(b){var e=[],a=0,d;if(!b)return[];if("string"!==typeof b)return[b];switch(b.charAt(0)){case "#":e.push(document.getElementById(b.substring(1)));break;case ".":var f=document.getElementsByTagName("*");for(d=" "+b.substring(1)+" ";a<f.length;a+=1)b=(" "+f[a].className+" ").replace(/[\n\t\r]/g," "),-1<b.indexOf(d)&&e.push(f[a]);
break;default:e=document.getElementsByTagName(b)}return e}},t={callbacks:{},L:c.global,fb:function(b){this.L=b},S:function(b,e,a,d,f){d=d||function(){};f||(f="cb");var g="cb"+h.Ya(),n=this;a[f]=this.L+".API.callbacks."+g;f=h.P();"file://"===f&&(f="http://");a[c.sb]=c.version;a=x.encode(a);var k=r.$(f+b+e+"?"+a);n.callbacks[g]=function(l){setTimeout(function(){k.parentNode&&k.parentNode.removeChild(k)},0);d(l);try{delete n.callbacks[g]}catch(p){n.callbacks[g]=null}}}},u={current:{}},y={U:{},za:function(b){var e=
document.cookie||"",a=this.U[b];a||(a=b.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),a=new RegExp("(?:^|;)\\s?"+a+"=(.*?)(?:;|$)","i"),this.U[b]=a);return(b=e.match(a))&&decodeURIComponent(b[1])},hb:function(b,e,a){var d="";a&&(d="; expires="+a.toGMTString());document.cookie=b+"="+e+d+"; path=/"},gc:function(b){this.hb(b,"",new Date(1982,5,13))}},w={ga:function(b){var e;var a=h.ib(b);a[c.A]&&(a[c.A]=h.C(a[c.A]));a[c.B]&&(a[c.B]=h.C(a[c.B]));a[c.I]&&(a[c.I]=h.C(a[c.I]));a[c.h]&&typeof a[c.h]!==c.H&&
(a[c.h]=a[c.h].toString());a[c.referrer]=""==a[c.G]?"":this.X(a[c.referrer]);a[c.G]=this.X(a[c.G]);a[c.T]=a[c.T]||window.location.toString();a[c.uid]?a[c.uid]=a[c.uid]:(e=this.ya())&&(a[c.uid]=e);a[c.url]&&(a[c.url]=this.Za(a[c.url]),b[c.url]=a[c.url]);return a},X:function(b){""!==b&&(b=b||r.xa());return b},ya:function(){return y.za(c.rb)},Za:function(b){if(0===b.indexOf("http%253A")||0===b.indexOf("https%253A"))b=decodeURIComponent(b);if(0===b.indexOf("http%3")||0===b.indexOf("https%3"))b=decodeURIComponent(b);
return b}},q=[c.v,c.Eb,c.La,c.h],z={create:function(b,e){return new v(b,e)},j:function(b,e){return this.create(b,e).j()}};return{video:function(b){return z.j(b)},debug:m,setLogLevel:function(b){m.gb(b)},API:t}}();window.SimplereachVideo;
